version: "3"
services:
  bompedido:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=bompedido
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432